/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FrServicesRouteImport } from './routes/fr/services'
import { Route as FrEquipementsRouteImport } from './routes/fr/equipements'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrAProposRouteImport } from './routes/fr/a-propos'
import { Route as EnServicesRouteImport } from './routes/en/services'
import { Route as EnEquipmentRouteImport } from './routes/en/equipment'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminMonCompteRouteImport } from './routes/admin/mon-compte'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEmployesRouteImport } from './routes/admin/employes'
import { Route as AdminDemandesRouteImport } from './routes/admin/demandes'
import { Route as AdminCommandesRouteImport } from './routes/admin/commandes'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminEquipementsIndexRouteImport } from './routes/admin/equipements/index'
import { Route as FrEquipementsSlugRouteImport } from './routes/fr/equipements_.$slug'
import { Route as EnEquipmentSlugRouteImport } from './routes/en/equipment_.$slug'
import { Route as AdminEquipementsNouveauRouteImport } from './routes/admin/equipements/nouveau'
import { Route as AdminEquipementsIdRouteImport } from './routes/admin/equipements/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FrServicesRoute = FrServicesRouteImport.update({
  id: '/fr/services',
  path: '/fr/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEquipementsRoute = FrEquipementsRouteImport.update({
  id: '/fr/equipements',
  path: '/fr/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAProposRoute = FrAProposRouteImport.update({
  id: '/fr/a-propos',
  path: '/fr/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEquipmentRoute = EnEquipmentRouteImport.update({
  id: '/en/equipment',
  path: '/en/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonCompteRoute = AdminMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployesRoute = AdminEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDemandesRoute = AdminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEquipementsIndexRoute = AdminEquipementsIndexRouteImport.update({
  id: '/equipements/',
  path: '/equipements/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FrEquipementsSlugRoute = FrEquipementsSlugRouteImport.update({
  id: '/fr/equipements_/$slug',
  path: '/fr/equipements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEquipmentSlugRoute = EnEquipmentSlugRouteImport.update({
  id: '/en/equipment_/$slug',
  path: '/en/equipment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipementsNouveauRoute = AdminEquipementsNouveauRouteImport.update({
  id: '/equipements/nouveau',
  path: '/equipements/nouveau',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEquipementsIdRoute = AdminEquipementsIdRouteImport.update({
  id: '/equipements/$id',
  path: '/equipements/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/employes': typeof AdminEmployesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mon-compte': typeof AdminMonCompteRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/admin/equipements/$id': typeof AdminEquipementsIdRoute
  '/admin/equipements/nouveau': typeof AdminEquipementsNouveauRoute
  '/en/equipment/$slug': typeof EnEquipmentSlugRoute
  '/fr/equipements/$slug': typeof FrEquipementsSlugRoute
  '/admin/equipements/': typeof AdminEquipementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/employes': typeof AdminEmployesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mon-compte': typeof AdminMonCompteRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/fr': typeof FrIndexRoute
  '/admin/equipements/$id': typeof AdminEquipementsIdRoute
  '/admin/equipements/nouveau': typeof AdminEquipementsNouveauRoute
  '/en/equipment/$slug': typeof EnEquipmentSlugRoute
  '/fr/equipements/$slug': typeof FrEquipementsSlugRoute
  '/admin/equipements': typeof AdminEquipementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/employes': typeof AdminEmployesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mon-compte': typeof AdminMonCompteRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/admin/equipements/$id': typeof AdminEquipementsIdRoute
  '/admin/equipements/nouveau': typeof AdminEquipementsNouveauRoute
  '/en/equipment_/$slug': typeof EnEquipmentSlugRoute
  '/fr/equipements_/$slug': typeof FrEquipementsSlugRoute
  '/admin/equipements/': typeof AdminEquipementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/demandes'
    | '/admin/employes'
    | '/admin/login'
    | '/admin/mon-compte'
    | '/admin/pages'
    | '/admin/parametres'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/admin/'
    | '/en/'
    | '/fr/'
    | '/admin/equipements/$id'
    | '/admin/equipements/nouveau'
    | '/en/equipment/$slug'
    | '/fr/equipements/$slug'
    | '/admin/equipements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/demandes'
    | '/admin/employes'
    | '/admin/login'
    | '/admin/mon-compte'
    | '/admin/pages'
    | '/admin/parametres'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/admin'
    | '/en'
    | '/fr'
    | '/admin/equipements/$id'
    | '/admin/equipements/nouveau'
    | '/en/equipment/$slug'
    | '/fr/equipements/$slug'
    | '/admin/equipements'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/commandes'
    | '/admin/demandes'
    | '/admin/employes'
    | '/admin/login'
    | '/admin/mon-compte'
    | '/admin/pages'
    | '/admin/parametres'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/admin/'
    | '/en/'
    | '/fr/'
    | '/admin/equipements/$id'
    | '/admin/equipements/nouveau'
    | '/en/equipment_/$slug'
    | '/fr/equipements_/$slug'
    | '/admin/equipements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  EquipementsRoute: typeof EquipementsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnEquipmentRoute: typeof EnEquipmentRoute
  EnServicesRoute: typeof EnServicesRoute
  FrAProposRoute: typeof FrAProposRoute
  FrContactRoute: typeof FrContactRoute
  FrEquipementsRoute: typeof FrEquipementsRoute
  FrServicesRoute: typeof FrServicesRoute
  EnIndexRoute: typeof EnIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  EnEquipmentSlugRoute: typeof EnEquipmentSlugRoute
  FrEquipementsSlugRoute: typeof FrEquipementsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/fr/services': {
      id: '/fr/services'
      path: '/fr/services'
      fullPath: '/fr/services'
      preLoaderRoute: typeof FrServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/equipements': {
      id: '/fr/equipements'
      path: '/fr/equipements'
      fullPath: '/fr/equipements'
      preLoaderRoute: typeof FrEquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/a-propos': {
      id: '/fr/a-propos'
      path: '/fr/a-propos'
      fullPath: '/fr/a-propos'
      preLoaderRoute: typeof FrAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/equipment': {
      id: '/en/equipment'
      path: '/en/equipment'
      fullPath: '/en/equipment'
      preLoaderRoute: typeof EnEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mon-compte': {
      id: '/admin/mon-compte'
      path: '/mon-compte'
      fullPath: '/admin/mon-compte'
      preLoaderRoute: typeof AdminMonCompteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employes': {
      id: '/admin/employes'
      path: '/employes'
      fullPath: '/admin/employes'
      preLoaderRoute: typeof AdminEmployesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/demandes': {
      id: '/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AdminDemandesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/equipements/': {
      id: '/admin/equipements/'
      path: '/equipements'
      fullPath: '/admin/equipements/'
      preLoaderRoute: typeof AdminEquipementsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/fr/equipements_/$slug': {
      id: '/fr/equipements_/$slug'
      path: '/fr/equipements/$slug'
      fullPath: '/fr/equipements/$slug'
      preLoaderRoute: typeof FrEquipementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/equipment_/$slug': {
      id: '/en/equipment_/$slug'
      path: '/en/equipment/$slug'
      fullPath: '/en/equipment/$slug'
      preLoaderRoute: typeof EnEquipmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipements/nouveau': {
      id: '/admin/equipements/nouveau'
      path: '/equipements/nouveau'
      fullPath: '/admin/equipements/nouveau'
      preLoaderRoute: typeof AdminEquipementsNouveauRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/equipements/$id': {
      id: '/admin/equipements/$id'
      path: '/equipements/$id'
      fullPath: '/admin/equipements/$id'
      preLoaderRoute: typeof AdminEquipementsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminDemandesRoute: typeof AdminDemandesRoute
  AdminEmployesRoute: typeof AdminEmployesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMonCompteRoute: typeof AdminMonCompteRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEquipementsIdRoute: typeof AdminEquipementsIdRoute
  AdminEquipementsNouveauRoute: typeof AdminEquipementsNouveauRoute
  AdminEquipementsIndexRoute: typeof AdminEquipementsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminDemandesRoute: AdminDemandesRoute,
  AdminEmployesRoute: AdminEmployesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMonCompteRoute: AdminMonCompteRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEquipementsIdRoute: AdminEquipementsIdRoute,
  AdminEquipementsNouveauRoute: AdminEquipementsNouveauRoute,
  AdminEquipementsIndexRoute: AdminEquipementsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  EquipementsRoute: EquipementsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnEquipmentRoute: EnEquipmentRoute,
  EnServicesRoute: EnServicesRoute,
  FrAProposRoute: FrAProposRoute,
  FrContactRoute: FrContactRoute,
  FrEquipementsRoute: FrEquipementsRoute,
  FrServicesRoute: FrServicesRoute,
  EnIndexRoute: EnIndexRoute,
  FrIndexRoute: FrIndexRoute,
  EnEquipmentSlugRoute: EnEquipmentSlugRoute,
  FrEquipementsSlugRoute: FrEquipementsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
