/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as FrServicesRouteImport } from './routes/fr/services'
import { Route as FrEquipementsRouteImport } from './routes/fr/equipements'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrAProposRouteImport } from './routes/fr/a-propos'
import { Route as EnServicesRouteImport } from './routes/en/services'
import { Route as EnEquipmentRouteImport } from './routes/en/equipment'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnAboutRouteImport } from './routes/en/about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrServicesRoute = FrServicesRouteImport.update({
  id: '/fr/services',
  path: '/fr/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEquipementsRoute = FrEquipementsRouteImport.update({
  id: '/fr/equipements',
  path: '/fr/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAProposRoute = FrAProposRouteImport.update({
  id: '/fr/a-propos',
  path: '/fr/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEquipmentRoute = EnEquipmentRouteImport.update({
  id: '/en/equipment',
  path: '/en/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/en': typeof EnIndexRoute
  '/fr': typeof FrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/equipment': typeof EnEquipmentRoute
  '/en/services': typeof EnServicesRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/equipements': typeof FrEquipementsRoute
  '/fr/services': typeof FrServicesRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/en/'
    | '/fr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/en'
    | '/fr'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/services'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/contact'
    | '/en/equipment'
    | '/en/services'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/equipements'
    | '/fr/services'
    | '/en/'
    | '/fr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  EquipementsRoute: typeof EquipementsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnEquipmentRoute: typeof EnEquipmentRoute
  EnServicesRoute: typeof EnServicesRoute
  FrAProposRoute: typeof FrAProposRoute
  FrContactRoute: typeof FrContactRoute
  FrEquipementsRoute: typeof FrEquipementsRoute
  FrServicesRoute: typeof FrServicesRoute
  EnIndexRoute: typeof EnIndexRoute
  FrIndexRoute: typeof FrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/services': {
      id: '/fr/services'
      path: '/fr/services'
      fullPath: '/fr/services'
      preLoaderRoute: typeof FrServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/equipements': {
      id: '/fr/equipements'
      path: '/fr/equipements'
      fullPath: '/fr/equipements'
      preLoaderRoute: typeof FrEquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/a-propos': {
      id: '/fr/a-propos'
      path: '/fr/a-propos'
      fullPath: '/fr/a-propos'
      preLoaderRoute: typeof FrAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/equipment': {
      id: '/en/equipment'
      path: '/en/equipment'
      fullPath: '/en/equipment'
      preLoaderRoute: typeof EnEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  EquipementsRoute: EquipementsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnEquipmentRoute: EnEquipmentRoute,
  EnServicesRoute: EnServicesRoute,
  FrAProposRoute: FrAProposRoute,
  FrContactRoute: FrContactRoute,
  FrEquipementsRoute: FrEquipementsRoute,
  FrServicesRoute: FrServicesRoute,
  EnIndexRoute: EnIndexRoute,
  FrIndexRoute: FrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
